/*
 *
 */
const config = {
  DYNAMODB_ENDPOINT: process.env.AWS_DYNAMODB_ENDPOINT,
  DYNAMODB_TABLE_TOP: process.env.NAPPI_TABLE_TOP,
  DYNAMODB_TABLE_TOP_COUNTER_IDX: -1,
  DYNAMODB_TABLE_TOP_MAX_SIZE: 7,
  MAX_WINNER_NAME_LENGTH: 32,
  DYNAMODB_MAX_DELETE_BATCH_SIZE: 20,
};

module.exports = config;
